LogInScreen Layout
BCSDLab/JJBAKSA-iOS pull request #1
Opened 2022-09-28 08:13 UTC by JeongYeongJoon

Design LogInScreen Layout
and
put Colors in Assets

2022-09-28 09:55 UTC, mero-jung requested changes
일단 간단하게 피드백 남겨두었습니다. 이따가 좀 더 자세히 남겨드리겠습니다.

일단 남겨준 feedback 참고하시고 다시 commit 올려주시면 될 것 같습니다.

2022-09-28 09:55 UTC, mero-jung commented on jjbaksa/Screens/LogIn/LogInScreen.swift
> +    }
해당 부분은 view보다는 viewmodel에서 정의해주는 게 좋을 것 같습니다.

사유: 기능 통일

2022-09-28 09:55 UTC, mero-jung commented on jjbaksa/Screens/LogIn/LogInScreen.swift
> +            .padding([.top], 114)
VStack 화면이 Scroll이 필요 없다면 가운데 정렬 방식을 이용하여 위, 아래에 Spacer를 두는 것도 다양한 해상도에 맞게 디자인이 가능할겁니다.

2022-09-28 09:55 UTC, mero-jung commented on jjbaksa/Screens/LogIn/LogInScreen.swift
> +                .padding(EdgeInsets(top: 105, leading: 81, bottom: 0, trailing: 257))
trailing의 경우 UI상 불필요한 부분이기에 0이어도 크게 문제가 없을겁니다. 오히려 trailing값을 정해져버리면 아이폰 SE같이 화면 width가 크지 않은 폰에서 화면 overflow가 일어날겁니다.

2022-09-30 08:26 UTC, mero-jung requested changes
디자인적인 부분은 크게 문제 없는 것 같아요.
이제 기능 관련된 부분만 개선하면 될 것 같아서 한번 리뷰 남긴 것 참고해주세요

2022-09-30 08:26 UTC, mero-jung commented on jjbaksa/Screens/LogIn/LogInScreen.swift
> +            .padding([.bottom], 7)
클릭 범위가 글자 정도밖에 없어서 한번 클릭 범위를 어떻게 넓힐지 생각해보시면 될 것 같습니다.

2022-09-30 08:26 UTC, mero-jung commented on jjbaksa/Screens/LogIn/LogInScreen.swift
>              TextField("아이디", text: $viewModel.account)
아이디 입력할 때 영어,숫자만 입력하게 해야할거에요. 그런 걸 제한할 수 있게 키보드 세팅을 해줘야할거라서 한번 찾아보시면 될거에요.

2022-09-30 08:26 UTC, mero-jung commented on jjbaksa/Screens/LogIn/LogInScreen.swift
>              SecureField("비밀번호", text: $viewModel.password)
비밀번호도 동일하게 영어, 숫자, 특수문자 일부만 입력되어야할 거에요.

2022-09-30 08:26 UTC, mero-jung commented on jjbaksa/Screens/LogIn/LogInScreen.swift
> +            //이 사이에 로그인 실패 메세지 출력
추후에 넣어야하거나 미완성된 기능은 주석에 
`// TODO: 이 사이에 로그인 실패 메세지 출력`
이렇게 해주면 나중에 참고할 때 편할거에요.

이 부분은 나중에 협업하면서 작업할 때 도움이 되는 부분이라 익히시면 좋으실거에요.

2022-09-30 08:26 UTC, mero-jung commented on jjbaksa/Screens/LogIn/ViewModels/LogInViewModel.swift
> +
단순히 값을 반환해주기만 하는 거면 function 형태로 주기보다는 

```swift
var infoNotEmptyCheck: Bool {
        !self.account.isEmpty && !self.password.isEmpty
    }
```
이런 형태로 해주면 더 효율적일거에요

2022-10-03 11:37 UTC, mero-jung requested changes

2022-10-03 11:37 UTC, mero-jung commented on jjbaksa/Screens/LogIn/LogInScreen.swift
> +                }
여기서 onChange를 이용해서 해도 괜찮겠지만, 전에 얘기 드렸던 것 처럼 view단에서 기능을 넣으면 통일성에 문제가 있을거에요. 그래서 viewmodel에 있는 변수에 set, didSet, WillSet을 주로 활용합니다. 관련 부분은 [이 링크](https://duwjdtn11.tistory.com/551)를 참고해보시고, 이건 제가 나중에 수정해둘게요.

2022-10-03 11:37 UTC, mero-jung commented on jjbaksa/Screens/LogIn/LogInScreen.swift
> +                }
아이디와 동일

2022-10-03 11:37 UTC, mero-jung commented on jjbaksa/Screens/LogIn/LogInScreen.swift
>              }
infoNotEmptyCheck로 로그인 색은 변경되게 했는데, action은 막지 않게 처리가 되었어요. viewmodel 부분에서 infoNotEmptyCheck가 true일때만 기능이 작동되게 하거나, action에서 !infoNotEmptyCheck이 true이면 action이 nil로 되게 해야할것 같아요.

2022-10-03 11:37 UTC, mero-jung commented on jjbaksa/Screens/LogIn/LogInScreen.swift
> +            Button(action: viewModel.logIn) {
소셜 로그인은 디자인 상으로 login이 되는 기능이 아니고, 화면이 이동하는 거라 임의로라도 login 기능을 붙이지 않는 게 좋아요. 나중에 배포되게 되면 테스트로 만든 기능을 그대로 넘어가게 되면 앱은 특히 심사 기간이 있다보니가 실수를 되돌리기 더 어렵거든요.

그래서 전에 얘기해둔 것처럼 미완성이거나 추후 작업 예정인 부분은
```swift
// TODO: 소셜 로그인 페이지 이동
```
이렇게 붙여서 다른 작업자들이 참고할 수 있게 주석을 달아주시면 됩니다.

2022-10-04 02:03 UTC, JeongYeongJoon commented on jjbaksa/Screens/LogIn/LogInScreen.swift
> +            }
padding을 넣어줘도 메세지 출력시 다른 view들이 밀리는 현상이 수정이 안되는데 방법을 모르겠습니다.

2022-10-04 02:05 UTC, mero-jung commented on jjbaksa/Screens/LogIn/LogInScreen.swift
> +            }
이 부분은 오늘 같이 얘기해보면 좋을 것 같아요. 그 때 피드백 드리겠습니다.

2022-10-04 12:17 UTC, mero-jung approved these changes

2022-10-04 12:32 UTC, merged